development:
  adapter: postgresql
  encoding: utf8
  database: sampleapp_development
  pool: 5
  username: user1
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sampleapp_test
  pool: 5
  username: user1
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: sampleapp_production
  pool: 5
  username: user1
  password: